-- Sample SQL
-- This file holds SQL statements that would be used ONLY by a user of Heat Clinic.
-- Admin permissions or additional, REQUIRED SQL should be included in src/main/resources/config/bc/sql
